<section id="right">
    <article id="content-cont">
        <p class="uppercase">Frank Owen Gehry, (born Frank Owen Goldberg; February 28, 1929) is a Canadian-American Pritzker Prize-winning architect based in Los Angeles. His buildings, including his private residence, have become tourist attractions. His works are cited as being among the most important works of contemporary architecture in the 2010 World Architecture Survey, which led Vanity Fair to label him as "the most important architect of our age".</p><br/>
<p>Gehry's best-known works include the titanium-covered Guggenheim Museum in Bilbao, Spain; MIT Ray and Maria Stata Center in Cambridge, Massachusetts; Walt Disney Concert Hall in downtown Los Angeles; Experience Music Project in Seattle; Weisman Art Museum in Minneapolis; Dancing House in Prague; the Vitra Design Museum and the museum MARTa Herford in Germany; the Art Gallery of Ontario in Toronto; the Cinémathèque française in Paris; and 8 Spruce Street in New York City. But it was his private residence in Santa Monica, California, that jump-started his career, lifting it from the status of "paper architecture"—a phenomenon that many famous architects have experienced in their formative decades through experimentation almost exclusively on paper before receiving their first major commission in later years. Gehry is also the designer of the future Dwight D. Eisenhower Memorial.</p><br/>
        <p>Gehry was born Frank Owen Goldberg on February 28, 1929, in Toronto, Ontario to parents, Irwin and Thelma (née Thelma Caplan) Goldberg. His parents were Polish Jews. A creative child, he was encouraged by his grandmother, Mrs. Caplan, with whom he would build little cities out of scraps of wood. With these scraps from her husband's hardware store, she entertained him for hours, building imaginary houses and futuristic cities on the living room floor. His use of corrugated steel, chain link fencing, unpainted plywood and other utilitarian or "everyday" materials was partly inspired by spending Saturday mornings at his grandfather's hardware store. He would spend time drawing with his father and his mother introduced him to the world of art. "So the creative genes were there", Gehry says. "But my mother thought I was a dreamer, I wasn't gonna amount to anything. It was my father who thought I was just reticent to do things. He would push me."</p><br/>
<p>In 1947 Gehry moved to California, got a job driving a delivery truck, and studied at Los Angeles City College, eventually to graduate from the University of Southern California's School of Architecture. According to Gehry: “I was a truck driver in L.A., going to City College, and I tried radio announcing, which I wasn't very good at. I tried chemical engineering, which I wasn't very good at and didn't like, and then I remembered. You know, somehow I just started racking my brain about, "What do I like?" Where was I? What made me excited? And I remembered art, that I loved going to museums and I loved looking at paintings, loved listening to music. Those things came from my mother, who took me to concerts and museums. I remembered Grandma and the blocks, and just on a hunch, I tried some architecture classes.”[8] In 1952 he married Anita Snyder, and in 1956 he changed his name to Frank O. Gehry at her suggestion, in part because of the anti-semitism he had experienced as a child and as an undergraduate at USC. Gehry graduated at the top of his class with a Bachelor of Architecture degree from USC in 1954. Afterwards, he spent time away from the field of architecture in numerous other jobs, including service in the United States Army. In the fall of 1956, he moved his family to Cambridge, where he studied city planning at the Harvard Graduate School of Design. He left before completing the program, disheartened and underwhelmed. Gehry's left-wing ideas about socially responsible architecture were under-realized, and the final straw occurred when he sat in on a discussion of one professor's "secret project in progress" - a palace that he was designing for right-wing Cuban Dictator Fulgencio Batista (1901-1973).[4] In 1966 he and Snyder divorced. In 1975 he married Panamanian Berta Isabel Aguilera, his current wife. He has two daughters from his first marriage, and two sons from his second marriage.</p><br/>
<p>Having grown up in Canada, Gehry is a huge fan of ice hockey. He began a hockey league in his office, FOG (which stands for Frank Owen Gehry), though he no longer plays with them.[citation needed] In 2004, he designed the trophy for the World Cup of Hockey.[citation needed] Gehry holds dual citizenship in Canada and the United States. He lives in Santa Monica, California, and continues to practice out of Los Angeles.</p>
        <div class="foot">
            <a href="#" id="work-thru" class="click-thru">More work by Gehry</a>
            <a href="moreabout.php" id="about-thru" class="click-thru">More about the architect</a>
        </div>
    </article>

</section>